#!/bin/zsh
set -e

# Helper to calculate simple expressions.
function _calc() {
    bc -q <<<"$1"
}

# Originally from https://github.com/FloorLamp/git-whatthecommit/blob/master/prepare-commit-msg
function __whatthecommit(){
  # First we grab a list of commit messages (we could possible cache this..) and then select 1 message
  # randomly which is sanitzed
  echo $(http GET https://raw.githubusercontent.com/ngerakines/commitment/master/commit_messages.txt \
        | sort -R \
        | head -n 1 \
        | sed "s/'/\\\'/g" \
    );
}

function __lock() {
    # Gets the (width, height) of the screen.
    read __screen_x __screen_y <<<$(xrandr -q | grep '*' | awk '{ split($1, res, "x"); print res[1], res[2];}')

    # Calculate the amount of pixelated blocks to show
    # Calculate the "reduced" height and width for the down-scaling.
    readonly __block_size=20
    readonly __reduced_x=$(_calc "${__screen_x} / ${__block_size}")
    readonly __reduced_y=$(_calc "${__screen_y} / ${__block_size}")

    readonly __message=$(__whatthecommit)
    readonly __icon="$HOME/.i3/assets/lock-icon.png"

    # Actually do the locking (generate the image without temporary files to not
    # clutter the filesystem). Since `convert -scale` doesn't do blurring, scaling
    # down and then back up is an efficient method of producing a pixelated image.
    i3lock $* -u -i <(import -screen -window root -silent png:- \
        | convert png:- -scale "${__reduced_x}x${__reduced_y}" -scale "${__screen_x}x${__screen_y}" \
          "${__icon}" -gravity center -geometry +0-50 -composite -matte \
          -gamma 1.0,1.3,1.0 \
          -gravity center -pointsize 50 -fill "#2ebd59" -draw "text 0,300 '"${__message}"'" png:- \
    )
}

__lock "$@"