#!/bin/sh

## Set startup volume
pactl set-sink-volume 0 '20%' &

## Disable beeps
xset -b &

## DPMS monitor setting (standby -> suspend -> off) (seconds)
xset dpms 300 900 1800 &

# Not sure if i should use it, but it will activate my fn keys:
gnome-settings-daemon &
